#!/bin/sh

# Packages

cd
pkg_add ansible
pkg_add automake
pkg_add bash
pkg_add ccl
pkg_add clisp
pkg_add curl
pkg_add emacs
pkg_add fish
pkg_add firefox
pkg_add git
pkg_add gnupg
pkg_add htop
pkg_add irssi
pkg_add links
pkg_add mercurial
pkg_add pianobar
pkg_add rxvt-unicode
pkg_add sbcl
pkg_add screenfetch
pkg_add sudo
pkg_add the_silver_searcher
pkg_add terminus-font
pkg_add wget

# Git repos

sudo -i -u enzuru sh << EOF
cd
rm -rf .emacs.d/
git clone --recurse-submodules -j8 https://github.com/enzuru/.emacs.d.git
git clone https://github.com/enzuru/org.git
git clone https://github.com/enzuru/lisp-machine.git
ln -s lisp-machine/openbsd/.Xresources .Xresources
ln -s lisp-machine/openbsd/.xsession .xsession
ln -s .emacs.d/folders folders
chsh -s /usr/local/bin/fish enzuru
git config --global user.name "Ahmed Khanzada"
git config --global user.email "me@enzu.ru"
git config --global core.editor "emacsclient"
EOF

# add enzuru to wheel and setup sudo
