#!/bin/sh

# Install -Y nvidia driver via ports

#cd /usr/ports/x11/nvidia-driver/
#make install -y clean
#nvidia-xconfig

# Packages

cd
pkg install -y autoconf
pkg install -y awscli
pkg install -y ansible
pkg install -y bash
pkg install -y bind-utils
pkg install -y chromium
pkg install -y ConsoleKit2
pkg install -y ccl
pkg install -y dbus
pkg install -y devel/py-game
pkg install -y devel/ruby-gems
pkg install -y docker
pkg install -y emacs
pkg install -y firefox
pkg install -y gcc
pkg install -y git
pkg install -y gimp
pkg install -y gotop
pkg install -y helm
pkg install -y htop
pkg install -y hwstat
pkg install -y irssi
pkg install -y jq
pkg install -y kubectl
pkg install -y lang/python3 # install -y pip somehow
pkg install -y links
pkg install -y mercurial
pkg install -y miniupnpc
pkg install -y nano
pkg install -y net/py-miniupnpc
pkg install -y npm
pkg install -y qemu
pkg install -y redshift
pkg install -y ruby
pkg install -y rxvt-unicode
pkg install -y sbcl
pkg install -y shells/fish
pkg install -y sudo
pkg install -y terraform
pkg install -y texinfo
pkg install -y the_silver_searcher
pkg install -y unzip
pkg install -y v41_compat
pkg install -y x11-fonts/terminus-font
pkg install -y x11-fonts/webfonts
pkg install -y xorg-fonts
pkg install -y xterm
pkg install -y xorg
pkg install -y xpdf
pkg install -y zfstools
pkg install -y zip

gem install irb

# Git repos

sudo -i -u enzuru sh << EOF
cd
rm -rf .emacs.d/
git clone --recurse-submodules -j8 https://github.com/enzuru/.emacs.d.git
git clone https://github.com/enzuru/org.git
git clone https://github.com/enzuru/lisp-machine.git
ln -s lisp-machine/freebsd/.Xresources .Xresources
ln -s lisp-machine/freebsd/.xinitrc .xinitrc
ln -s .emacs.d/folders folders
chsh -s /usr/local/bin/fish enzuru
git config --global user.name "Ahmed Khanzada"
git config --global user.email "me@enzu.ru"
git config --global core.editor "emacsclient"
EOF

cd /home/enzuru
cp lisp-machine/freebsd/rc.conf /etc/rc.conf
cp lisp-machine/freebsd/loader.conf /boot/loader.conf
cp lisp-machine/freebsd/sysctl.conf /etc/sysctl.conf
cp lisp-machine/freebsd/xorg.conf /etc/X11/xorg.conf

# add enzuru to wheel and setup sudo
